In [1]:
%matplotlib widget

In [3]:
from rayoptics.environment import *

from opticalglass.glassfactory import get_glass_catalog
from opticalglass.glass import get_glass_map_arrays

schott = get_glass_catalog('Schott')
nd, vd, PFd, bc1, bc2, names = get_glass_map_arrays(schott, 'd', 'F', 'C')

In [4]:
nd

array([1.62004, 1.62004, 1.60342, 1.48748, 1.50137, 1.51112, 1.7495 ,
       2.02204, 1.58144, 1.58144, 1.54814, 1.54815, 1.67003, 1.60568,
       1.65224, 1.60863, 1.5725 , 1.53996, 1.56883, 1.56883, 1.57956,
       1.54739, 1.66446, 1.704  , 1.49782, 1.5168 , 1.5168 , 1.5168 ,
       1.62005, 1.48749, 1.48656, 1.456  , 1.52249, 1.52346, 1.63775,
       1.55836, 1.61336, 1.61336, 1.65412, 1.72047, 1.74397, 1.788  ,
       1.78582, 1.7725 , 1.7433 , 1.7495 , 1.72003, 1.6779 , 1.6968 ,
       1.64049, 1.65113, 1.755  , 1.72916, 1.6516 , 1.713  , 1.691  ,
       1.883  , 1.83404, 1.83501, 1.8061 , 1.8042 , 1.80107, 1.80107,
       1.90366, 1.90366, 1.85025, 1.85025, 1.52855, 1.497  , 1.55232,
       1.618  , 1.71736, 1.72828, 1.78472, 1.76182, 1.69892, 1.64769,
       1.75513, 1.67271, 1.84666, 1.84666, 1.84666, 1.80518, 1.92286,
       1.80518, 1.80518, 1.68894, 1.56384, 1.60311, 1.62041, 1.60738,
       1.60738, 1.61272, 1.58913, 1.62229, 1.65844, 1.61773, 1.50847,
       1.50805, 1.51

In [5]:
PFd

array([0.70615836, 0.70615836, 0.70554855, 0.69030391, 0.69628796,
       0.69503546, 0.70582751, 0.71026443, 0.70414617, 0.7044335 ,
       0.70200334, 0.70184255, 0.70112518, 0.7032491 , 0.70227429,
       0.70137825, 0.6971831 , 0.69579646, 0.69685039, 0.69685039,
       0.69795539, 0.69735553, 0.70693391, 0.70453274, 0.69086022,
       0.69230769, 0.69230769, 0.69230769, 0.70681551, 0.69075145,
       0.69444444, 0.69322709, 0.69589977, 0.6988189 , 0.70013298,
       0.6934236 , 0.69956459, 0.69956459, 0.7026699 , 0.7061657 ,
       0.70223026, 0.6992164 , 0.70123318, 0.69813744, 0.69833887,
       0.70724907, 0.69711876, 0.69788274, 0.69530628, 0.69512195,
       0.69699571, 0.6966759 , 0.69581465, 0.69541779, 0.69584906,
       0.695962  , 0.70267775, 0.70527728, 0.70144628, 0.70277078,
       0.69982649, 0.7069869 , 0.7069869 , 0.70883882, 0.70883882,
       0.7086644 , 0.7086644 , 0.69577875, 0.69458128, 0.69310345,
       0.69538462, 0.71056978, 0.7112069 , 0.71325696, 0.71239

In [6]:
from mpl_toolkits.mplot3d import Axes3D

In [7]:
fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')

ax.scatter(vd, nd, PFd)

ax.set_xlabel('Vd')
ax.set_ylabel('nd')
ax.set_zlabel('PFd')

plt.show()

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [8]:
fig2 = plt.figure()
ax2 = fig2.add_subplot(111, projection='3d')

ax2.scatter(bc1, bc2, nd)

ax2.set_xlabel('bc1')
ax2.set_ylabel('bc2')
ax2.set_zlabel('nd')

ax2.set_proj_type('ortho')
ax2.azim = -39.3
ax2.elev = -4.7

plt.show()

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [9]:
type(ax2)

matplotlib.axes._subplots.Axes3DSubplot

In [10]:
from scipy import linalg

In [11]:
num_glasses = len(nd)
a = np.array([[bc1[i], bc2[i], 1] for i in range(num_glasses)])
b = nd

results = linalg.lstsq(a, b)
coefs = results[0]

In [12]:
coefs

array([-6.65379567, -7.56733038,  1.20518231])

In [13]:
results

(array([-6.65379567, -7.56733038,  1.20518231]),
 0.09729403411427304,
 3,
 array([11.1361212 ,  0.55570976,  0.06631719]))

In [14]:
m = len(nd)
X = np.array([bc1, bc2, nd])

In [15]:
A = np.array([np.sum(X[0])/m, np.sum(X[1])/m, np.sum(X[2])/m])

In [16]:
np.sqrt(np.dot(A, A))

1.6821339900009429

In [17]:
Y = X.T - A.T

In [18]:
m00 = np.sum((X[0] - A[0])**2)
m01 = np.sum((X[0] - A[0])*(X[1] - A[1]))
m02 = np.sum((X[0] - A[0])*(X[2] - A[2]))
m11 = np.sum((X[1] - A[1])**2)
m12 = np.sum((X[1] - A[1])*(X[2] - A[2]))
m22 = np.sum((X[2] - A[2])**2)

In [19]:
MA = np.array([[m00, m01, m02], [m01, m11, m12], [m02, m12, m22]])
MA

array([[ 0.23590775, -0.13190933, -0.57148045],
       [-0.13190933,  0.0795625 ,  0.27562199],
       [-0.57148045,  0.27562199,  1.81408549]])

In [20]:
EA = linalg.eig(MA, right=True); EA

(array([2.04595832e+00+0.j, 8.28110805e-02+0.j, 7.86342930e-04+0.j]),
 array([[-0.30763986,  0.71182628, -0.63139612],
        [ 0.15228623, -0.618189  , -0.77113634],
        [ 0.93923726,  0.33338521, -0.08177823]]))

In [21]:
EA[0]

array([2.04595832e+00+0.j, 8.28110805e-02+0.j, 7.86342930e-04+0.j])

In [22]:
EA[1]

array([[-0.30763986,  0.71182628, -0.63139612],
       [ 0.15228623, -0.618189  , -0.77113634],
       [ 0.93923726,  0.33338521, -0.08177823]])

In [23]:
fig3 = plt.figure()
for column in range(3):

    N = EA[1].T[column]

    d = -np.dot(N, A)

    elev = np.degrees(np.arcsin(N[2]))
    cos_elev = np.cos(np.arcsin(N[2]))
    azi = np.degrees(np.arcsin(N[0]/cos_elev))
    azi, elev

    ax3 = fig3.add_subplot(1, 3, column+1, projection='3d')

    ax3.scatter(X[0], X[1], X[2],
                c=X[2], cmap=mpl.cm.get_cmap('rainbow'),
                norm=mpl.colors.Normalize(vmin=np.min(X[2]), vmax=np.max(X[2])))

    ax3.set_xlabel('bc1')
    ax3.set_ylabel('bc2')
    ax3.set_zlabel('nd')

    ax3.set_proj_type('ortho')
    ax3.azim = azi
    ax3.elev = elev

plt.show()

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [24]:
A, d

(array([-0.08927283,  0.01579107,  1.67968919]), 0.09317256882270203)

In [25]:
mpl.cm

<module 'matplotlib.cm' from '/Users/Mike/Developer/miniconda3/envs/og_dev/lib/python3.8/site-packages/matplotlib/cm.py'>

In [26]:
def PCA(data, correlation = False, sort = True):
    """ Applies Principal Component Analysis to the data

    Parameters
    ----------        
    data: array
        The array containing the data. The array must have NxM dimensions, where each
        of the N rows represents a different individual record and each of the M columns
        represents a different variable recorded for that individual record.
            array([
            [V11, ... , V1m],
            ...,
            [Vn1, ... , Vnm]])

    correlation(Optional) : bool
            Set the type of matrix to be computed (see Notes):
                If True compute the correlation matrix.
                If False(Default) compute the covariance matrix. 

    sort(Optional) : bool
            Set the order that the eigenvalues/vectors will have
                If True(Default) they will be sorted (from higher value to less).
                If False they won't.   
    Returns
    -------
    eigenvalues: (1,M) array
        The eigenvalues of the corresponding matrix.

    eigenvector: (M,M) array
        The eigenvectors of the corresponding matrix.

    Notes
    -----
    The correlation matrix is a better choice when there are different magnitudes
    representing the M variables. Use covariance matrix in other cases.
    https://stackoverflow.com/a/38770513

    """

    mean = np.mean(data, axis=0)

    data_adjust = data - mean

    #: the data is transposed due to np.cov/corrcoef syntax
    if correlation:

        matrix = np.corrcoef(data_adjust.T)

    else:
        matrix = np.cov(data_adjust.T) 

    eigenvalues, eigenvectors = np.linalg.eig(matrix)

    if sort:
        #: sort eigenvalues and eigenvectors
        sort = eigenvalues.argsort()[::-1]
        eigenvalues = eigenvalues[sort]
        eigenvectors = eigenvectors[:,sort]

    return eigenvalues, eigenvectors

In [27]:
def best_fitting_plane(points, equation=False):
    """ Computes the best fitting plane of the given points

    Parameters
    ----------        
    points: array
        The x,y,z coordinates corresponding to the points from which we want
        to define the best fitting plane. Expected format:
            array([
            [x1,y1,z1],
            ...,
            [xn,yn,zn]])

    equation(Optional) : bool
            Set the oputput plane format:
                If True return the a,b,c,d coefficients of the plane.
                If False(Default) return 1 Point and 1 Normal vector.    
    Returns
    -------
    a, b, c, d : float
        The coefficients solving the plane equation.

    or

    point, normal: array
        The plane defined by 1 Point and 1 Normal vector. With format:
        array([Px,Py,Pz]), array([Nx,Ny,Nz])
        https://stackoverflow.com/a/38770513

    """

    w, v = PCA(points, correlation=True)

    #: the normal of the plane is the last eigenvector
    normal = v[:,2]

    #: get a point from the plane
    point = np.mean(points, axis=0)


    if equation:
        a, b, c = normal
        d = -(np.dot(normal, point))
        return a, b, c, d

    else:
        return point, normal

In [28]:
point, normal = best_fitting_plane(X.T)

In [29]:
point, normal

(array([-0.08927283,  0.01579107,  1.67968919]),
 array([-0.78456539, -0.54869295, -0.2887788 ]))

In [30]:
A

array([-0.08927283,  0.01579107,  1.67968919])

In [31]:
point, normal = best_fitting_plane(X.T); point, normal

(array([-0.08927283,  0.01579107,  1.67968919]),
 array([-0.78456539, -0.54869295, -0.2887788 ]))

In [32]:
fig4 = plt.figure()
for column in range(3):

    N = normal

    d = -np.dot(N, A)

    elev = np.degrees(np.arcsin(N[2]))
    cos_elev = np.cos(np.arcsin(N[2]))
    azi = np.degrees(np.arcsin(N[0]/cos_elev))
    azi, elev

    ax4 = fig4.add_subplot(1, 3, column+1, projection='3d')

    ax4.scatter(X[0], X[1], X[2],
                c=X[2], cmap=mpl.cm.get_cmap('rainbow'),
                norm=mpl.colors.Normalize(vmin=np.min(X[2]), vmax=np.max(X[2])))

    ax4.set_xlabel('bc1')
    ax4.set_ylabel('bc2')
    ax4.set_zlabel('nd')

    ax4.set_proj_type('ortho')
    ax4.azim = azi
    ax4.elev = elev

plt.show()

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [33]:
f2 = create_glass('F2', 'Schott')

In [35]:
n_calc_D = f2.rindex(f'D')
n_meas_D = f2.meas_rindex('D')
n_calc_D, n_meas_D

(1.6198910300169231, 1.61989)

In [36]:
f2.calc_rindex(np.array([589.5924, 589.2937, 588.9950]))

array([1.61986546, 1.61989104, 1.61991665])

In [37]:
get_wavelength('D')

589.2938

In [38]:
j_bk7a = create_glass('J-BK7A', 'Hikari')

In [41]:
n_calc_t = j_bk7a.rindex('t')
n_meas_Fp = j_bk7a.meas_rindex("F'")
n_calc_t, n_meas_Fp

(1.507356122880302, 1.522836)